import type { Metadata } from "next";
import { Barlow_Condensed } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";
import Footer from "@/components/shared/Footer";
import WorkoutProvider from "@/context/workoutContext";
import { ToastContainer } from "react-toastify";

const barlow = Barlow_Condensed({
  variable: "--font-barlow",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${barlow.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col font-[var(--font-barlow)]">

        <WorkoutProvider>
          <Navbar />

          {children}

          <Footer />

          <ToastContainer />
        </WorkoutProvider>

      </body>
    </html>
  );
}
